
name: 'Update Database'

on:
  push:
    paths:
      - launch_actions.txt
  schedule:
    - cron:  '00 * * * *'

jobs:
  get-data-update-db:
    if: contains( github.ref, 'main' )
    runs-on: ubuntu-20.04
    steps:
      - name: Clone Repo
        uses: actions/checkout@v3
        with:
          path: ${{runner.workspace}}/my_house_data/
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip' # caching pip dependencies

      - name: Install dependencies
        working-directory: ${{runner.workspace}}/my_house_data/
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run script
        working-directory: ${{runner.workspace}}/my_house_data/
        env:
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          SECRET: ${{ secrets.SECRET }}
        run: |
          python get_data.py

      - name: Save
        working-directory: ${{runner.workspace}}/my_house_data/
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add datapoints.csv
          git commit -m "Update DB" --allow-empty
          git push

  generate-plot:
    if: contains( github.ref, 'main' )
    needs: get-data-update-db
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Clone Repo
        uses: actions/checkout@v3
        with:
          path: ${{runner.workspace}}/my_house_data/
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip' # caching pip dependencies

      - name: Install dependencies
        working-directory: ${{runner.workspace}}/my_house_data/
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run script
        working-directory: ${{runner.workspace}}/my_house_data/
        run: |
          python plot_plotly.py

      - name: Save
        working-directory: ${{runner.workspace}}/my_house_data/
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git pull
          git add docs/index.html
          git commit -m "Update plots" --allow-empty
          git push
